[theme]
base = "light"
primaryColor = "#b30000"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f0ef"
textColor = "#1a1a1a"
borderColor = "#e6dada"
font = "sans serif"

[server]
headless = true
port = 8501
